"""Додано поле profile_picture в таблицю user

Revision ID: 54682a8a4a77
Revises: 
Create Date: 2025-03-16 18:39:02.659547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54682a8a4a77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))
        batch_op.drop_column('profile')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', sa.NUMERIC(), nullable=True))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
