"""Додано поле aes_key_encrypted у таблицю user

Revision ID: 5bd3d6263d11
Revises: 54682a8a4a77
Create Date: 2025-03-16 21:06:18.328554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd3d6263d11'
down_revision = '54682a8a4a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aes_key_encrypted', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('aes_key_encrypted')

    # ### end Alembic commands ###
